import test from 'node:test';
import assert from 'node:assert/strict';
import {COLORS,TASTES,newSession,payloadFor,validatePayload,validateState} from '../js/core.js';
const id='12345678-1234-1234-1234-123456789abc';
function complete(){const s=newSession('TEST_001',25,id);s.blocks[0].startedAt='2026-10-01T00:00:00.000Z';s.blocks[0].scores=COLORS.map(c=>c.colorId%6);s.blocks[0].payload=payloadFor(s,0,'2026-10-01T00:01:00.000Z');return s;}
test('150 exact unique HSL colors and original dark order',()=>{assert.equal(COLORS.length,150);assert.equal(new Set(COLORS.map(c=>`${c.h}/${c.s}/${c.l}`)).size,150);assert.deepEqual(COLORS.slice(8,12).map(c=>c.s),[100,75,50,25]);assert.deepEqual(COLORS.slice(144).map(c=>c.l),[100,80,60,40,20,0]);});
test('new sessions are permutations and reload preserves orders',()=>{for(let i=0;i<50;i++){const s=newSession('TEST_001',25,id);assert.deepEqual([...s.blocks.map(b=>b.taste)].sort(),[...TASTES].sort());for(const b of s.blocks)assert.deepEqual([...b.order].sort((a,b)=>a-b),COLORS.map(c=>c.colorId));assert.ok(validateState(JSON.parse(JSON.stringify(s))));}});
test('score zero preserved; presentation order is distinct from canonical ID',()=>{const s=complete();const p=s.blocks[0].payload;assert.ok(validatePayload(p));assert.equal(p.colors.find(c=>c.colorId===6).score,0);assert.deepEqual(p.colors.map(c=>c.presentationOrder),COLORS.map(c=>c.colorId));assert.ok(validateState(s));});
test('reject wrong HSL, duplicate IDs, missing/unrated/out-of-range colors, ST',()=>{const p=complete().blocks[0].payload;for(const mutate of [p=>p.colors.pop(),p=>p.colors[0].score=null,p=>p.colors[0].score=6,p=>p.colors[0].h=361,p=>p.colors[0].colorId=p.colors[1].colorId,p=>p.method='ST',p=>p.colors[0].presentationOrder=0,p=>p.subjectId='=HYPERLINK("x")',p=>p.age=NaN,p=>p.tasteSequence[1]=p.tasteSequence[0]]){const q=structuredClone(p);mutate(q);assert.throws(()=>validatePayload(q));}});
test('frozen completed payload cannot diverge from saved answers',()=>{const s=complete();s.blocks[0].scores[0]=5;assert.throws(()=>validateState(s));});
test('all 6 blocks and 900 scores survive serialized resume',()=>{const s=newSession('001',30,id);for(let i=0;i<6;i++){s.blocks[i].startedAt='2026-10-01T00:00:00.000Z';s.blocks[i].scores=COLORS.map(c=>c.colorId%6);s.blocks[i].payload=payloadFor(s,i,'2026-10-01T00:01:00.000Z');assert.ok(validateState(s));}assert.ok(validateState(JSON.parse(JSON.stringify(s))));assert.equal(s.blocks.reduce((n,b)=>n+b.payload.colors.length,0),900);});
