import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import crypto from 'node:crypto';
import {newSession,payloadFor} from '../js/core.js';
const code=fs.readFileSync(new URL('../google-apps-script/Code.gs',import.meta.url),'utf8');
function fixture(){
 const sheets=new Map(),props={SPREADSHEET_ID:'test-only',ACCEPTING_RESPONSES:'true'};let held=false;
 class Sheet{constructor(){this.rows=[];this.cols=26;this.maxRows=1000;}getMaxColumns(){return this.cols;}insertColumnsAfter(_,n){this.cols+=n;}getMaxRows(){return this.maxRows;}insertRowsAfter(_,n){this.maxRows+=n;}getLastRow(){return this.rows.length;}setFrozenRows(){}getRange(r,c,n,m){return {setValues:v=>{assert.equal(held,true);for(let i=0;i<n;i++){this.rows[r-1+i]??=[];for(let j=0;j<m;j++)this.rows[r-1+i][c-1+j]=v[i][j];}},getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>this.rows[r-1+i]?.[c-1+j]??'')),setNumberFormat:()=>{}};}}
 const ss={getSheetByName:n=>sheets.get(n),insertSheet:n=>{const s=new Sheet();sheets.set(n,s);return s;}};
 const ctx=vm.createContext({PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k]})},SpreadsheetApp:{openById:()=>ss,flush:()=>{}},LockService:{getScriptLock:()=>({waitLock:()=>{assert.equal(held,false);held=true;},hasLock:()=>held,releaseLock:()=>held=false})},ContentService:{MimeType:{JSON:'json'},createTextOutput:s=>({setMimeType:()=>JSON.parse(s)})},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_,s)=>[...crypto.createHash('sha256').update(s).digest()]}});
 vm.runInContext(code,ctx);ctx.setup();return {ctx,sheets,props,post:p=>ctx.doPost({postData:{contents:JSON.stringify(p)}})};
}
function p(){const s=newSession('001',27,'12345678-1234-1234-1234-123456789abc');s.blocks[0].startedAt='2026-10-01T00:00:00.000Z';s.blocks[0].scores.fill(0);return payloadFor(s,0,'2026-10-01T00:01:00.000Z');}
test('save and ambiguous network retry: only one canonical row, same receipt',()=>{const f=fixture(),data=p();const a=f.post(data),b=f.post(data);assert.equal(a.ok,true);assert.equal(b.duplicate,true);assert.equal(a.digest,b.digest);assert.equal(a.digest,crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex'));assert.equal(f.sheets.get('Responses').rows.length,2);const r=f.sheets.get('Responses').rows[1];assert.equal(r[6],'001');assert.equal(r[15],0);assert.equal(r.length,315);});
test('same key with changed answer is rejected',()=>{const f=fixture(),data=p();f.post(data);data.colors[0].score=5;assert.equal(f.post(data).ok,false);assert.equal(f.sheets.get('Responses').rows.length,2);});
test('invalid payload and disabled intake do not append',()=>{const f=fixture(),data=p();data.colors[0].h=999;assert.equal(f.post(data).ok,false);f.props.ACCEPTING_RESPONSES='false';assert.equal(f.post(p()).ok,false);assert.equal(f.sheets.get('Responses').rows.length,1);});
test('allowlist, unchanged headers, server-held configuration',()=>{const f=fixture();f.props.ALLOWED_SUBJECT_IDS='OTHER';assert.equal(f.post(p()).ok,false);f.props.ALLOWED_SUBJECT_IDS='001';assert.equal(f.post(p()).ok,true);f.ctx.setup();assert.equal(f.sheets.get('Responses').rows.length,2);assert.equal(f.sheets.get('Palette').rows.length,151);});
test('same session cannot change subject/age/sequence',()=>{const f=fixture(),data=p();f.post(data);data.tasteOrder=2;data.taste=data.tasteSequence[1];data.age=28;assert.equal(f.post(data).ok,false);});
